// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MesPro.proto

package srcs;

public final class MesPro {
  private MesPro() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_user_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_user_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_srcs_mes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_srcs_mes_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MesPro.proto\022\004srcs\032\036google/protobuf/wr" +
      "appers.proto\032\033google/protobuf/empty.prot" +
      "o\"2\n\004user\022\020\n\010username\030\001 \001(\t\022\n\n\002ip\030\002 \001(\t\022" +
      "\014\n\004port\030\003 \001(\t\"(\n\003mes\022\020\n\010username\030\001 \001(\t\022\017" +
      "\n\007message\030\002 \001(\t2\365\001\n\004Chat\0223\n\tsubscribe\022\n." +
      "srcs.user\032\032.google.protobuf.BoolValue\022.\n" +
      "\004send\022\t.srcs.mes\032\033.google.protobuf.Int32" +
      "Value\022C\n\013listChatter\022\026.google.protobuf.E" +
      "mpty\032\034.google.protobuf.StringValue\022C\n\013un" +
      "subscribe\022\034.google.protobuf.StringValue\032" +
      "\026.google.protobuf.Empty2B\n\017MessageReceiv" +
      "er\022/\n\nnewMessage\022\t.srcs.mes\032\026.google.pro" +
      "tobuf.EmptyB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_srcs_user_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_srcs_user_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_user_descriptor,
        new java.lang.String[] { "Username", "Ip", "Port", });
    internal_static_srcs_mes_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_srcs_mes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_srcs_mes_descriptor,
        new java.lang.String[] { "Username", "Message", });
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
