// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MesPro.proto

package srcs;

public interface userOrBuilder extends
    // @@protoc_insertion_point(interface_extends:srcs.user)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <code>string ip = 2;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string port = 3;</code>
   * @return The port.
   */
  java.lang.String getPort();
  /**
   * <code>string port = 3;</code>
   * @return The bytes for port.
   */
  com.google.protobuf.ByteString
      getPortBytes();
}
